package ai.nexuzy.assistant.llm

// ============================================================
//  MLCEngineWrapper
//  Adapted from: mlc-ai/mlc-llm/android/MLCChat/AppViewModel.kt
//  https://github.com/mlc-ai/mlc-llm/tree/main/android/MLCChat
//  License: Apache 2.0
// ============================================================
//
//  HOW mlc4j IS GENERATED (the correct way):
//
//  mlc4j is NOT copied from the repo manually.
//  It is GENERATED by the MLC build pipeline:
//
//    # Install MLC-LLM Python package
//    pip install mlc-llm
//
//    # Place mlc-package-config.json in project root (already done)
//    # Run the packager — this compiles .so libs + generates dist/lib/mlc4j
//    python3 -m mlc_llm package
//
//  After that:
//    dist/lib/mlc4j    ← Android library module (the mlc4j module)
//    dist/bundle/      ← compiled model weights
//
//  Then in settings.gradle uncomment:
//    include ':mlc4j'
//    project(':mlc4j').projectDir = file('dist/lib/mlc4j')
//
//  In app/build.gradle uncomment:
//    implementation project(':mlc4j')
//
//  Below set:  MLC_AVAILABLE = true
//  Uncomment:  the 3 import lines
// ============================================================

import android.content.Context
import android.util.Log
import kotlinx.coroutines.*
import java.io.File
import java.io.FileOutputStream
import java.net.URL
import java.nio.channels.Channels
import java.util.concurrent.Executors

// Uncomment after `python3 -m mlc_llm package` + settings.gradle setup:
// import ai.mlc.mlcllm.MLCEngine
// import ai.mlc.mlcllm.OpenAIProtocol
// import ai.mlc.mlcllm.OpenAIProtocol.ChatCompletionMessage

class MLCEngineWrapper(private val context: Context) {

    companion object {
        // Change to true after completing `python3 -m mlc_llm package` setup
        const val MLC_AVAILABLE = false
        const val TAG = "MLCEngineWrapper"
    }

    // Uncomment after setup:
    // private val engine = MLCEngine()

    private val executor = Executors.newSingleThreadExecutor()
    private val scope = CoroutineScope(Dispatchers.Main + Job())
    private val appDirFile = context.getExternalFilesDir("") ?: context.filesDir

    var onStateChange: ((EngineState) -> Unit)? = null
    var onTokenStream: ((String) -> Unit)? = null
    private var currentState = EngineState.NOT_LOADED

    enum class EngineState { NOT_LOADED, LOADING, READY, GENERATING, FAILED }

    // ----------------------------------------------------------------
    // loadModel() — mirrors AppViewModel.ChatState.mainReloadChat()
    //   engine.unload()  → unload previous model
    //   engine.reload(modelPath, modelLib)  → load new model
    // modelPath = absolute path to model weights directory on device
    // modelLib  = model_lib key from mlc-package-config.json
    // ----------------------------------------------------------------
    fun loadModel(modelId: String, modelLib: String) {
        if (!MLC_AVAILABLE) { setState(EngineState.NOT_LOADED); return }
        setState(EngineState.LOADING)
        val modelPath = File(appDirFile, modelId).absolutePath
        executor.submit {
            try {
                // engine.unload()
                // engine.reload(modelPath, modelLib)
                scope.launch { setState(EngineState.READY) }
            } catch (e: Exception) {
                Log.e(TAG, "Load failed: ${e.message}")
                scope.launch { setState(EngineState.FAILED) }
            }
        }
    }

    // ----------------------------------------------------------------
    // generate() — mirrors AppViewModel.ChatState.requestGenerate()
    //   Uses OpenAI-compatible streaming: engine.chat.completions.create()
    //   Each chunk: choice.delta.content?.asText() = one token
    //   Invokes onTokenStream(token) per token for live UI update
    // ----------------------------------------------------------------
    suspend fun generate(
        prompt: String,
        history: List<Pair<String, String>> = emptyList()
    ): String = withContext(Dispatchers.IO) {
        if (!MLC_AVAILABLE || currentState != EngineState.READY)
            return@withContext fallbackResponse(prompt)

        setState(EngineState.GENERATING)
        val sb = StringBuilder()
        try {
            // val messages = mutableListOf<ChatCompletionMessage>()
            // history.forEach { (u, a) ->
            //     messages += ChatCompletionMessage(
            //         role = OpenAIProtocol.ChatCompletionRole.user,
            //         content = OpenAIProtocol.ChatCompletionMessageContent(text = u)
            //     )
            //     messages += ChatCompletionMessage(
            //         role = OpenAIProtocol.ChatCompletionRole.assistant,
            //         content = a
            //     )
            // }
            // messages += ChatCompletionMessage(
            //     role = OpenAIProtocol.ChatCompletionRole.user,
            //     content = OpenAIProtocol.ChatCompletionMessageContent(text = prompt)
            // )
            // val responses = engine.chat.completions.create(
            //     messages = messages,
            //     stream_options = OpenAIProtocol.StreamOptions(include_usage = true)
            // )
            // for (res in responses) {
            //     for (choice in res.choices) {
            //         choice.delta.content?.let { c ->
            //             val token = c.asText()
            //             sb.append(token)
            //             scope.launch { onTokenStream?.invoke(token) }
            //         }
            //         // AppViewModel also checks finish_reason == "length"
            //         choice.finish_reason?.let { reason ->
            //             if (reason == "length") sb.append(" [truncated]")
            //         }
            //     }
            //     // Usage stats (tokens/sec) from res.usage
            //     res.usage?.let { scope.launch {
            //         // update report label: it.extra?.asTextLabel()
            //     }}
            // }
        } catch (e: Exception) {
            Log.e(TAG, "Generate error: ${e.message}")
            setState(EngineState.READY)
            return@withContext "Error: ${e.message}"
        }
        setState(EngineState.READY)
        sb.toString()
    }

    fun resetChat() {
        // Mirrors AppViewModel.ChatState.mainResetChat()
        // engine.reset() clears KV cache without unloading weights
        if (MLC_AVAILABLE) executor.submit { /* engine.reset() */ }
    }

    fun unload() {
        // Mirrors AppViewModel.ChatState.mainTerminateChat()
        // engine.unload() frees VRAM
        if (MLC_AVAILABLE) executor.submit {
            // engine.unload()
            scope.launch { setState(EngineState.NOT_LOADED) }
        }
    }

    // ----------------------------------------------------------------
    // downloadModel() — mirrors AppViewModel.ModelState download logic
    // Downloads mlc-chat-config.json + tensor shards from HuggingFace
    // Production: use `python3 -m mlc_llm package` instead (builds+packs)
    // ----------------------------------------------------------------
    fun downloadModel(
        modelId: String,
        modelUrl: String,
        onProgress: (Int, Int) -> Unit,
        onComplete: () -> Unit,
        onError: (String) -> Unit
    ) {
        val modelDir = File(appDirFile, modelId).also { it.mkdirs() }
        executor.submit {
            try {
                val configFile = File(modelDir, "mlc-chat-config.json")
                if (!configFile.exists()) {
                    URL("$modelUrl/resolve/main/mlc-chat-config.json").openStream().use { input ->
                        FileOutputStream(configFile).use { out ->
                            Channels.newChannel(input).use { src ->
                                out.channel.transferFrom(src, 0, Long.MAX_VALUE)
                            }
                        }
                    }
                }
                scope.launch { onComplete() }
            } catch (e: Exception) {
                scope.launch { onError(e.message ?: "Download failed") }
            }
        }
    }

    private fun setState(s: EngineState) { currentState = s; onStateChange?.invoke(s) }
    fun getState() = currentState

    private fun fallbackResponse(prompt: String): String {
        val toolLine = prompt.lines().firstOrNull {
            it.startsWith("Current weather") || it.startsWith("Latest news") ||
            it.startsWith("Alarm") || it.startsWith("Flashlight") ||
            it.startsWith("Media") || it.startsWith("•")
        }
        return toolLine?.trim()
            ?: "💡 Qwen3 not ready. Run: python3 -m mlc_llm package  (see SETUP_GUIDE.md)"
    }
}
